[[protocols]]
name = "xoro_hrk_7660"
protocol = "nec"
variant = "nec"
[protocols.scancodes]
0xbf16 = "KEY_DOWN"
0xbf06 = "KEY_UP"
0xbf5a = "KEY_LEFT"
0xbf1b = "KEY_RIGHT"
0xbf0f = "KEY_NUMERIC_0"
0xbf52 = "KEY_NUMERIC_1"
0xbf50 = "KEY_NUMERIC_2"
0xbf10 = "KEY_NUMERIC_3"
0xbf56 = "KEY_NUMERIC_4"
0xbf54 = "KEY_NUMERIC_5"
0xbf14 = "KEY_NUMERIC_6"
0xbf4e = "KEY_NUMERIC_7"
0xbf4c = "KEY_NUMERIC_8"
0xbf0c = "KEY_NUMERIC_9"
0xbf01 = "KEY_VOLUMEUP"
0xbf02 = "KEY_VOLUMEDOWN"
0xbf0d = "KEY_CHANNELUP"
0xbf11 = "KEY_CHANNELDOWN"
0xbf1a = "KEY_OK"
0xbf04 = "KEY_STOP"
0xbf07 = "KEY_RECORD"
0xbf46 = "KEY_PLAY"
0xbf44 = "KEY_PAUSE"
0xbf4d = "KEY_EPG"
0xbf18 = "KEY_TEXT"
0xbf19 = "KEY_MUTE"
0xbf03 = "KEY_BLUE"
0xbf00 = "KEY_YELLOW"
0xbf42 = "KEY_RED"
0xbf40 = "KEY_GREEN"
0xbf15 = "KEY_RADIO"
0xbf59 = "KEY_POWER"
0xbf05 = "KEY_EXIT"
0xbf45 = "KEY_MENU"
0xbf08 = "KEY_PREVIOUS"
0xbf0b = "KEY_NEXT"
0xbf48 = "KEY_FASTFORWARD"
0xbf4a = "KEY_REWIND"
0xbf0e = "KEY_GOTO"